<%@ page language="java" contentType="text/xml; charset=UTF-8"
    pageEncoding="UTF-8"%>

 <users>
 	<user>
 		<id>java01</id>
 		<name>홍길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java02</id>
 		<name>고길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java03</id>
 		<name>박길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java04</id>
 		<name>최길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java05</id>
 		<name>김길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java06</id>
 		<name>이길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java07</id>
 		<name>나길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>java08</id>
 		<name>길동</name>
 		<email>java@naver.com</email>
 	</user>
 	<user>
 		<id>admin</id>
 		<name>관리자</name>
 		<email>java@naver.com</email>
 	</user>

 </users>